### ISSUE TITLE
Wires – snap to grid

### ISSUE THREAD

**Issue by umbertocerrato** [kazuhikoarase/simcirjs#18]
Hi,

Do you thought about how I can make the wires to snap to the grid in order to have an organized view?

**Comment by kazuhikoarase** [comment]
What do you mean the grip?

**Comment by umbertocerrato** [comment]
Grid, I meant grid! Fun fact is that I wrote “grip” both in the title and description...

**Comment by kazuhikoarase** [comment]
The Joint component may help you. 

![s-layout](https://user-images.githubusercontent.com/1137546/94790030-b1912780-0410-11eb-913d-a4409028c65a.png)

**Comment by umbertocerrato** [comment]
Wow
Thank you so much.

**Comment by umbertocerrato** [comment]
Is it possible to rotate the components too? (This was another thing I could not understand)
