### ISSUE TITLE
Can I message you?

### ISSUE THREAD

**Issue by umbertocerrato** [kazuhikoarase/simcirjs#19]

**Comment by kazuhikoarase** [comment]
Hi, 
I see your message.

> I would like to create a “Toggle” button but with input and output on top and bottom of the rect.

I recommend you to read a source below.
The updateUI function layout an input node and an output node by direction.

https://github.com/kazuhikoarase/simcirjs/blob/master/misc/simcir-num.js

```javascript
          if (type == 'src') {
            $s.transform(out1.$ui, x1, y1);
            $point.attr({cx : x1, cy : y1});
          } else if (type == 'dsp') {
            $s.transform(in1.$ui, x1, y1);
          }
```

**Comment by umbertocerrato** [comment]
Thank you very very much.

I will look into it as soon as possible.

I did not see those file too…

Thank you a lot again!

Cheers

**Comment by umbertocerrato** [comment]
Thank you very much.

I have just seen the NumSrc device and honestly I do not have any more reason to go deeper in the understanding of the code since NumSrc is the perfect component for what I was doing! Thank you again, I like simcir very very much. I can’t wait of finding other inputs to study the code again and learn it/play with it.

Best,
Umberto

PS:
This is the circuit I have been building if you want to give it a look; it was for a school homework. (The exercise was on paper only but I decided to simulate it through simcir too ;) ) http://home.macintosh.garden/~mepy2/scuola.html

Also if you see in the “controllers”, still there are the DC + Toggle buttons. I think I will leave them there though, it would require some time to replace them with NumSrc devices too :)
