### ISSUE TITLE
Direct, single segment, connection lines make for messy circuits

### ISSUE THREAD

**Issue by JamesNewton** [kazuhikoarase/simcirjs#2]
For example, the JK flip flop sample is very hard to understand because of the connection lines crossing over things. 

Suggestion: Add an ondoubleclick handler for connection lines that splits the line and inserts a buffer gate. However, this buffer gate is drawn as a single dot or small circle which has both input and output on top of each other. It has an "invisible" area around it (could be square) by which it can be moved though dragging with mouse.

**Comment by JamesNewton** [comment]
I am very please to see you are doing some updates to this project. I would really love to port over my tutorial to this simulator (it uses java applet now, which only works in IE) but the lines really can't be as they are because it quickly becomes too confusing. 
http://techref.massmind.org/techref/logic/tutorial.htm

**Comment by JamesNewton** [comment]
It looks like the new "buffer gate" would actually best be descended from the input / output ports, with a different class for the changed appearance. Something would have to be changed to make sure they were not seen as IO ports... I couldn't find that in the code. And I'm not sure how to make the input and output points be in the middle instead of the edges.

**Comment by kazuhikoarase** [comment]
Hi,

I have just added a new device named 'small buffer'.
You can use it directly or with customize.

https://github.com/kazuhikoarase/simcirjs/blob/master/simcir-small-buf.js
https://kazuhikoarase.github.io/simcirjs/#-KYONcjENTHvfjOW3tX6

Thank you.

**Comment by JamesNewton** [comment]
Well, that's not ideal, but it's good enough! This new version of the flip flop circuit looks MUCH better, I think:
https://kazuhikoarase.github.io/simcirjs/#-KYPQAENRAs8PM22u8N_

I will try over the holidays to set this up and start translating the tutorial into it on my site. You are welcomed to copy and host the tutorial on your site as well, if you wish.

Just a silly thought: I notice that the label for the new part doesn't show. This is good because you don't want a label there for a wire. However, if the label DID show, but was initially set to nothing, then the label could be used to add text descriptions into the circuit. E.g. to add notes. Perhaps that should be a different device...

**Comment by kazuhikoarase** [comment]
Oops...
It was oscillating because 'small buffer' delays a signal.
So I fixed it.
Please get a latest modules.

Thank you.
