### ISSUE TITLE
Change colour if connector is enabled

### ISSUE THREAD

**Issue by icecoldfire** [kazuhikoarase/simcirjs#5]
I'm using this fantastic tool for visualising electronics circuits, but I want to change the colour of a network if it is enabled. So that a network that is on has green wires and that a network that is disabled has red wires, is this possible?

**Comment by kazuhikoarase** [comment]
Hi,
I think a network on the workspace is always enabled.
What state did you mean that a network is disabled?

**Comment by icecoldfire** [comment]
I mean with disabled that the cable is on state 0 (off). A cable that is disabled can maybe have the colour red? An green cable would mean than that the cable is on state 1.

This will give the possibility for seeing  what the port now does with the input cables.

**Comment by kazuhikoarase** [comment]
Nodes change a color according to state(red or black).
Would you want see also with a color of cable?

**Comment by icecoldfire** [comment]
Yes that would help with complicated circuits

**Comment by kazuhikoarase** [comment]
I have tried to do.

Download latest from 

https://github.com/kazuhikoarase/simcirjs/archive/master.zip

and modify simcir.css line 54 as follows.

```css
.simcir-connector-hot {
  /* stroke: #ff0000; */
  stroke: #ff0000;
}
```
