### ISSUE TITLE
Add propagation delay

### ISSUE THREAD

**Issue by datusm** [kazuhikoarase/simcirjs#7]
Can you add a propagation delay to the sim so that I can demo rising and falling edge detection circuits and edge trigger ff's?

Great tool...thanks for making it public!

**Comment by kazuhikoarase** [comment]
Hi,
I added a new device named 'Delay' (short red line).
https://kazuhikoarase.github.io/simcirjs/#-KpYsZON225_X-JiI9YX

**Comment by datusm** [comment]
Thank you...I really appreciate your work and I see it on your demo page at https://kazuhikoarase.github.io/simcirjs/, but when I download and put the zip file from github on my server, the sample.html does not have the new options (and when I try to copy the html from the active webpage, it also does not work). Is there a corrupted file on gethub?

**Comment by kazuhikoarase** [comment]
sample.html does not include optional devices.
You have to open the file with text editor and add line as follows.
```html
<script type="text/javascript" src="simcir-library.js"></script>
<!-- start add -->
<script type="text/javascript" src="misc/simcir-delay.js"></script>
<!-- end add -->
<style type="text/css">
```

**Comment by datusm** [comment]
Thank you again....it is working just as I need!
I appreciate it!

Thank you
Daniel KohnUniversity of MemphisMemphis TN



On Saturday, July 22, 2017, 4:32:57 PM CDT, kazuhiko arase <notifications@github.com> wrote:


sample.html does not include optional devices.
You have to open the file with text editor and add line as follows.
<script type="text/javascript" src="simcir-library.js"></script>

<script type="text/javascript" src="misc/simcir-delay.js"></script>

<style type="text/css">
